#!/usr/bin/env bash

print_help() {
    echo "Usage: rehash-lcm-gen [-o] inputlcm"
    echo "Generate CPP message defn with overridden hash value specified in input file"
    echo "  -o      Override autosrc publisher to use rehashed message definition."
    echo "  -h      Print this help and exit"
}

PRINTHELP=false
OFLAG=''
while getopts ':oh' flag; do
  case "${flag}" in
    o) OFLAG='true'; echo " * Using overridden messages in republishers" >&2 ;;
    h) PRINTHELP=true ;;
    \?) echo "Invalid option: -$OPTARG" >&2 ;;
  esac
done

shift $((OPTIND-1))

if [ $# -eq 0 ] || [ "$PRINTHELP" = true ] ; then
    print_help
    exit 2
fi

for INFILE in "$@" ; do
    echo "Processing input file: $INFILE" >&2

    # Create cpp header using lcm-gen
    # lcm-gen -x $INFILE
    
    TOPIC_NAME=$(echo $INFILE | sed 's:lcm/::; s/.lcm//')
    MESSAGE_TYPE=$(cat $INFILE | awk '/struct/ {print $2}')
    OLD_PACKAGE_NAME=$(cat $INFILE | awk '/package/ {print $2}' | sed "s/;//g")
    NEW_PACKAGE_NAME=$OLD_PACKAGE_NAME"_rehash"
    HASH_VALUE=$(cat $INFILE | awk '/HASH/ {print $3}')

    if [ -z "$HASH_VALUE" ] ; then
        echo "No valid hash value found in $INFILE, returning" >&2
        continue
    fi
            
    mkdir -p $NEW_PACKAGE_NAME

    # Create new hpp with overridden hash methods
    OUTFILE="$NEW_PACKAGE_NAME/$MESSAGE_TYPE.hpp"
    echo " Creating new header $OUTFILE with overridden hash methods." >&2
    echo " Message type:     $MESSAGE_TYPE" >&2
    echo " Old package name: $OLD_PACKAGE_NAME" >&2
    echo " New package name: $NEW_PACKAGE_NAME" >&2
    echo " New hash value:   $HASH_VALUE" >&2

    echo $(printf '/%.0s' {1..71}) > $OUTFILE
    echo "// This message was automatically generated by rehash-lcm-gen" >>$OUTFILE
    echo "// https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu" >>$OUTFILE
    echo -e "$(printf '/%.0s' {1..71})\n//" >>$OUTFILE
    echo "// Source message:    $MESSAGE_TYPE.msg" >> $OUTFILE
    echo "// Creation:          $(date '+%c')" >> $OUTFILE
    echo -e "//\n$(printf '/%.0s' {1..71})" >>$OUTFILE

    # Create sed replace string for replacing placeholders
    REPSTR="s:@NEW_PACKAGE_NAME@:$NEW_PACKAGE_NAME:; "
    REPSTR=$REPSTR"s:@OLD_PACKAGE_NAME@:$OLD_PACKAGE_NAME:; "
    REPSTR=$REPSTR"s:@MESSAGE_TYPE@:$MESSAGE_TYPE:g; "
    REPSTR=$REPSTR"s:@HASH@:$HASH_VALUE:"

    # Append the replaced hpp to the output file
    cat src/lcm_rehash.hpp.in | sed  "${REPSTR}" >> $OUTFILE
    
    # Force the autosrc republisher to use the rehashed message
    if [ -n "$OFLAG"  ] ; then
        REPUBFILE="autosrc/${TOPIC_NAME}_republisher.cpp"
        if [ -e "$REPUBFILE" ] ; then
            echo " Editing republisher to use overridden hash methods." >&2
            sed -i "s:${OLD_PACKAGE_NAME}/:$NEW_PACKAGE_NAME/:g" $REPUBFILE
            sed -i "s/${OLD_PACKAGE_NAME}::/$NEW_PACKAGE_NAME::/g" $REPUBFILE
        else
            echo " Republisher $REPUBFILE not found!" >&2
        fi
    fi
done
