#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "usage: rehash-lcm-gen inputlcm"
fi

INFILE=$1
echo "Processing input file: $INFILE"

# Create cpp header using lcm-gen
lcm-gen -x $INFILE

MESSAGE_TYPE=$(cat $INFILE | awk '/struct/ {print $2}')
OLD_PACKAGE_NAME=$(cat $INFILE | awk '/package/ {print $2}' | sed "s/;//g")
NEW_PACKAGE_NAME=$OLD_PACKAGE_NAME"_rehash"
HASH_VALUE=$(cat $INFILE | awk '/HASH/ {print $3}')

if [ -z "$HASH_VALUE" ]
    then
        echo "No valid hash value found in $INFILE, returning"
        exit 1
fi
        
mkdir -p $NEW_PACKAGE_NAME

# Create new hpp with overriden hash methods
OUTFILE="$NEW_PACKAGE_NAME/$MESSAGE_TYPE.hpp"
echo " Creating new header $OUTFILE with overriden hash methods."
echo " Message type:     $MESSAGE_TYPE"
echo " Old package name: $OLD_PACKAGE_NAME"
echo " New package name: $NEW_PACKAGE_NAME"
echo " New hash value:   $HASH_VALUE"

echo $(printf '/%.0s' {1..71}) > $OUTFILE
echo "// This message was automatically generated by rehash-lcm-gen" >>$OUTFILE
echo "// https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu" >>$OUTFILE
echo -e "$(printf '/%.0s' {1..71})\n//" >>$OUTFILE
echo "// Source message:    $MESSAGE_TYPE.msg" >> $OUTFILE
echo "// Creation:          $(date '+%c')" >> $OUTFILE
echo -e "//\n$(printf '/%.0s' {1..71})" >>$OUTFILE

# Create sed replace string for replacing placeholders
REPSTR="s:@NEW_PACKAGE_NAME@:$NEW_PACKAGE_NAME:; "
REPSTR=$REPSTR"s:@OLD_PACKAGE_NAME@:$OLD_PACKAGE_NAME:; "
REPSTR=$REPSTR"s:@MESSAGE_TYPE@:$MESSAGE_TYPE:g; "
REPSTR=$REPSTR"s:@HASH@:$HASH_VALUE:"

# Append the replaced hpp to the output file
cat src/lcm_rehash.hpp.in | sed  "${REPSTR}" >> $OUTFILE

echo " Done."
