#!/usr/bin/env bash

OFLAG=''
while getopts ':o' flag; do
  case "${flag}" in
    o) OFLAG='true'; echo "** Using overridden messages in republishers **" ;;
    \?) echo "Invalid option: -$OPTARG" ;;
  esac
done

shift $((OPTIND-1))

if [ $# -eq 0 ] ; then
    echo "Usage: rehash-lcm-gen [-o] inputlcm"
    echo "  -o      Override autosrc publisher to use rehashed message definition."
    exit 2
fi

for INFILE in "$@" ; do
    echo "Processing input file: $INFILE"

    # Create cpp header using lcm-gen
    # lcm-gen -x $INFILE
    
    TOPIC_NAME=$(echo $INFILE | sed 's:lcm/::; s/.lcm//')
    MESSAGE_TYPE=$(cat $INFILE | awk '/struct/ {print $2}')
    OLD_PACKAGE_NAME=$(cat $INFILE | awk '/package/ {print $2}' | sed "s/;//g")
    NEW_PACKAGE_NAME=$OLD_PACKAGE_NAME"_rehash"
    HASH_VALUE=$(cat $INFILE | awk '/HASH/ {print $3}')

    if [ -z "$HASH_VALUE" ] ; then
        echo "No valid hash value found in $INFILE, returning"
        continue
    fi
            
    mkdir -p $NEW_PACKAGE_NAME

    # Create new hpp with overriden hash methods
    OUTFILE="$NEW_PACKAGE_NAME/$MESSAGE_TYPE.hpp"
    echo " Creating new header $OUTFILE with overriden hash methods."
    echo " Message type:     $MESSAGE_TYPE"
    echo " Old package name: $OLD_PACKAGE_NAME"
    echo " New package name: $NEW_PACKAGE_NAME"
    echo " New hash value:   $HASH_VALUE"

    echo $(printf '/%.0s' {1..71}) > $OUTFILE
    echo "// This message was automatically generated by rehash-lcm-gen" >>$OUTFILE
    echo "// https://github.com/nrjl/lcm_to_ros, nicholas.lawrance@oregonstate.edu" >>$OUTFILE
    echo -e "$(printf '/%.0s' {1..71})\n//" >>$OUTFILE
    echo "// Source message:    $MESSAGE_TYPE.msg" >> $OUTFILE
    echo "// Creation:          $(date '+%c')" >> $OUTFILE
    echo -e "//\n$(printf '/%.0s' {1..71})" >>$OUTFILE

    # Create sed replace string for replacing placeholders
    REPSTR="s:@NEW_PACKAGE_NAME@:$NEW_PACKAGE_NAME:; "
    REPSTR=$REPSTR"s:@OLD_PACKAGE_NAME@:$OLD_PACKAGE_NAME:; "
    REPSTR=$REPSTR"s:@MESSAGE_TYPE@:$MESSAGE_TYPE:g; "
    REPSTR=$REPSTR"s:@HASH@:$HASH_VALUE:"

    # Append the replaced hpp to the output file
    cat src/lcm_rehash.hpp.in | sed  "${REPSTR}" >> $OUTFILE
    
    # Force the autosrc republisher to use the rehashed message
    if [ -n "$OFLAG"  ] ; then
        echo " Editing republisher to use overridden hash methods."
        sed -i "s:${OLD_PACKAGE_NAME}/:$NEW_PACKAGE_NAME/:g" "autosrc/${TOPIC_NAME}_republisher.cpp"
        sed -i "s/${OLD_PACKAGE_NAME}::/$NEW_PACKAGE_NAME::/g" "autosrc/${TOPIC_NAME}_republisher.cpp"

    fi

    echo " Done."
done
